/* Generated By:JavaCC: Do not edit this line. JsonParserGenerateConstants.java */
package net.sf.sojo.interchange.json.generate;

public interface JsonParserGenerateConstants {

  int EOF = 0;
  int TRUE = 5;
  int FALSE = 6;
  int NULL = 7;
  int EXPONENT = 8;
  int NUMBER = 9;
  int STRING = 10;
  int DOUBLE_STRING_CHARACTERS = 11;
  int DOUBLE_STRING_CHARACTER = 12;
  int DOUBLE_SLASH = 13;
  int ESCAPE_SEQUENCE = 14;
  int CHARACTER_ESCAPE_SEQUENCE = 15;
  int SINGLE_ESCAPE_CHARACTER = 16;
  int NON_ESCAPE_CHARACTER = 17;
  int EOL = 18;

  int DEFAULT = 0;
  int ESC = 1;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"true\"",
    "\"false\"",
    "\"null\"",
    "<EXPONENT>",
    "<NUMBER>",
    "<STRING>",
    "<DOUBLE_STRING_CHARACTERS>",
    "<DOUBLE_STRING_CHARACTER>",
    "\"\\\\\"",
    "<ESCAPE_SEQUENCE>",
    "<CHARACTER_ESCAPE_SEQUENCE>",
    "<SINGLE_ESCAPE_CHARACTER>",
    "<NON_ESCAPE_CHARACTER>",
    "\";\"",
    "\"{\"",
    "\":\"",
    "\",\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
  };

}
